/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.controladorPrincipal;
import java.io.File;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import modelo.vo.Albums;
import modelo.vo.Users;

/**
 *
 * @author AD
 */
public class Principal extends javax.swing.JFrame {
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        controladorPrincipal.iniciaSession();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        frmAlbums = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbAlbums = new javax.swing.JComboBox<>();
        txtAlbumNombre = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        btnImagen = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAnhadirAlbum = new javax.swing.JButton();
        btnModificarAlbum = new javax.swing.JButton();
        btnBorrarAlbum = new javax.swing.JButton();
        txtImagen = new javax.swing.JLabel();
        fileChooser = new javax.swing.JFileChooser();
        frmListados = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        txtListarEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtListarGenero = new javax.swing.JTextField();
        btnListarGenero = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnListarUsuarios = new javax.swing.JButton();
        btnListarAlbums = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnListarPlayed = new javax.swing.JButton();
        btnListarListenLIst = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListarArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        cmbUser = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtContrasenha = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAnhadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAlbums = new javax.swing.JMenuItem();
        mnuListas = new javax.swing.JMenuItem();

        frmAlbums.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                frmAlbumsWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                frmAlbumsWindowOpened(evt);
            }
        });
        frmAlbums.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("Album:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmAlbums.getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmAlbums.getContentPane().add(jLabel6, gridBagConstraints);

        jLabel7.setText("Autor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmAlbums.getContentPane().add(jLabel7, gridBagConstraints);

        jLabel8.setText("Genero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmAlbums.getContentPane().add(jLabel8, gridBagConstraints);

        jLabel9.setText("Fecha de Salida:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmAlbums.getContentPane().add(jLabel9, gridBagConstraints);

        jLabel10.setText("Imagen:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmAlbums.getContentPane().add(jLabel10, gridBagConstraints);

        cmbAlbums.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAlbumsItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmAlbums.getContentPane().add(cmbAlbums, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmAlbums.getContentPane().add(txtAlbumNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmAlbums.getContentPane().add(txtAutor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmAlbums.getContentPane().add(txtGenero, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmAlbums.getContentPane().add(txtFecha, gridBagConstraints);

        btnImagen.setText("Seleccionar");
        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmAlbums.getContentPane().add(btnImagen, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnAnhadirAlbum.setText("Añadir");
        btnAnhadirAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhadirAlbumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(btnAnhadirAlbum, gridBagConstraints);

        btnModificarAlbum.setText("Modificar");
        btnModificarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAlbumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(btnModificarAlbum, gridBagConstraints);

        btnBorrarAlbum.setText("Borrar");
        btnBorrarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarAlbumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(btnBorrarAlbum, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 6;
        frmAlbums.getContentPane().add(jPanel2, gridBagConstraints);

        txtImagen.setMaximumSize(new java.awt.Dimension(200, 200));
        txtImagen.setPreferredSize(new java.awt.Dimension(150, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        frmAlbums.getContentPane().add(txtImagen, gridBagConstraints);

        frmListados.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                frmListadosWindowClosing(evt);
            }
        });
        frmListados.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel11.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmListados.getContentPane().add(jLabel11, gridBagConstraints);

        txtListarEmail.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmListados.getContentPane().add(txtListarEmail, gridBagConstraints);

        jLabel12.setText("Genero:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmListados.getContentPane().add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmListados.getContentPane().add(txtListarGenero, gridBagConstraints);

        btnListarGenero.setText("Listar Albums Genero");
        btnListarGenero.setPreferredSize(new java.awt.Dimension(100, 23));
        btnListarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarGeneroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmListados.getContentPane().add(btnListarGenero, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnListarUsuarios.setText("Listar Usuarios");
        btnListarUsuarios.setPreferredSize(new java.awt.Dimension(165, 23));
        btnListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarUsuariosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel3.add(btnListarUsuarios, gridBagConstraints);

        btnListarAlbums.setText("Listar Albums");
        btnListarAlbums.setPreferredSize(new java.awt.Dimension(165, 23));
        btnListarAlbums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAlbumsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel3.add(btnListarAlbums, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        frmListados.getContentPane().add(jPanel3, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        btnListarPlayed.setText("Listar 'Played' Albums");
        btnListarPlayed.setPreferredSize(new java.awt.Dimension(165, 23));
        btnListarPlayed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPlayedActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(btnListarPlayed, gridBagConstraints);

        btnListarListenLIst.setText("Listar 'ListenList' Albums");
        btnListarListenLIst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarListenLIstActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel4.add(btnListarListenLIst, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        frmListados.getContentPane().add(jPanel4, gridBagConstraints);

        txtListarArea.setColumns(20);
        txtListarArea.setRows(5);
        jScrollPane1.setViewportView(txtListarArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        frmListados.getContentPane().add(jScrollPane1, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(360, 250));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel1, gridBagConstraints);

        cmbUser.setPreferredSize(new java.awt.Dimension(120, 22));
        cmbUser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUserItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(cmbUser, gridBagConstraints);

        jLabel2.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(txtNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(txtContrasenha, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnAnhadir.setText("Añadir");
        btnAnhadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhadirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btnAnhadir, gridBagConstraints);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btnModificar, gridBagConstraints);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btnBorrar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel4.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(txtEmail, gridBagConstraints);

        jMenu1.setText("Apartados");

        mnuAlbums.setText("Albums");
        mnuAlbums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlbumsActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAlbums);

        mnuListas.setText("Listas");
        mnuListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuListas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        controladorPrincipal.cerrarSession();
    }//GEN-LAST:event_formWindowClosed

    private void btnAnhadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhadirActionPerformed
        controladorPrincipal.anhadirUsuario();
    }//GEN-LAST:event_btnAnhadirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        controladorPrincipal.modificarUsuario();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cmbUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUserItemStateChanged
        controladorPrincipal.cargarUsuario();
    }//GEN-LAST:event_cmbUserItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        controladorPrincipal.cargarCombo();
        controladorPrincipal.cargarUsuario();
    }//GEN-LAST:event_formWindowOpened

    private void mnuAlbumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlbumsActionPerformed
        this.setVisible(false);
        frmAlbums.setVisible(true);
        frmAlbums.setSize(500, 500);
        frmAlbums.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnuAlbumsActionPerformed

    private void frmAlbumsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frmAlbumsWindowClosing
        this.setVisible(true);
    }//GEN-LAST:event_frmAlbumsWindowClosing

    private void btnImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenActionPerformed
        controladorPrincipal.seleccionarImagen();
    }//GEN-LAST:event_btnImagenActionPerformed

    private void frmAlbumsWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frmAlbumsWindowOpened
        controladorPrincipal.cargarComboAlbums();
        controladorPrincipal.cargarAlbum();
    }//GEN-LAST:event_frmAlbumsWindowOpened

    private void btnAnhadirAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhadirAlbumActionPerformed
        controladorPrincipal.anhadirAlbum();
    }//GEN-LAST:event_btnAnhadirAlbumActionPerformed

    private void cmbAlbumsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAlbumsItemStateChanged
        controladorPrincipal.cargarAlbum();
    }//GEN-LAST:event_cmbAlbumsItemStateChanged

    private void btnModificarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAlbumActionPerformed
        controladorPrincipal.modificarAlbum();
    }//GEN-LAST:event_btnModificarAlbumActionPerformed

    private void btnBorrarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarAlbumActionPerformed
        controladorPrincipal.borrarAlbum();
    }//GEN-LAST:event_btnBorrarAlbumActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        controladorPrincipal.borrarUsuario();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void mnuListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListasActionPerformed
        this.setVisible(false);
        frmListados.setVisible(true);
        frmListados.setSize(400, 350);
        frmListados.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnuListasActionPerformed

    private void frmListadosWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frmListadosWindowClosing
        this.setVisible(true);
    }//GEN-LAST:event_frmListadosWindowClosing

    private void btnListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarUsuariosActionPerformed
        controladorPrincipal.listarUsuarios();
    }//GEN-LAST:event_btnListarUsuariosActionPerformed

    private void btnListarAlbumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAlbumsActionPerformed
        controladorPrincipal.listarAlbums();
    }//GEN-LAST:event_btnListarAlbumsActionPerformed

    private void btnListarPlayedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPlayedActionPerformed
        controladorPrincipal.listarPlayedAlbums();
    }//GEN-LAST:event_btnListarPlayedActionPerformed

    private void btnListarListenLIstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarListenLIstActionPerformed
        controladorPrincipal.listarListenListAlbums();
    }//GEN-LAST:event_btnListarListenLIstActionPerformed

    private void btnListarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarGeneroActionPerformed
        controladorPrincipal.listarAlbumGenero();
    }//GEN-LAST:event_btnListarGeneroActionPerformed

    public JTextField getTxtContrasenha() {
        return txtContrasenha;
    }

    public void setTxtContrasenha(JTextField txtContrasenha) {
        this.txtContrasenha = txtContrasenha;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }    

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public JComboBox<Users> getCmbUser() {
        return cmbUser;
    }

    public void setCmbUser(JComboBox<Users> cmbUser) {
        this.cmbUser = cmbUser;
    }

    public JComboBox<Albums> getCmbAlbums() {
        return cmbAlbums;
    }

    public void setCmbAlbums(JComboBox<Albums> cmbAlbums) {
        this.cmbAlbums = cmbAlbums;
    }

    public JTextField getTxtAlbumNombre() {
        return txtAlbumNombre;
    }

    public void setTxtAlbumNombre(JTextField txtAlbumNombre) {
        this.txtAlbumNombre = txtAlbumNombre;
    }

    public JTextField getTxtAutor() {
        return txtAutor;
    }

    public void setTxtAutor(JTextField txtAutor) {
        this.txtAutor = txtAutor;
    }

    public JTextField getTxtFecha() {
        return txtFecha;
    }

    public void setTxtFecha(JTextField txtFecha) {
        this.txtFecha = txtFecha;
    }

    public JTextField getTxtGenero() {
        return txtGenero;
    }

    public void setTxtGenero(JTextField txtGenero) {
        this.txtGenero = txtGenero;
    }

    public JLabel getTxtImagen() {
        return txtImagen;
    }

    public void setTxtImagen(JLabel txtImagen) {
        this.txtImagen = txtImagen;
    }

    public JFileChooser getFileChooser() {
        return fileChooser;
    }

    public void setFileChooser(JFileChooser fileChooser) {
        this.fileChooser = fileChooser;
    }

    public JTextArea getTxtListarArea() {
        return txtListarArea;
    }

    public void setTxtListarArea(JTextArea txtListarArea) {
        this.txtListarArea = txtListarArea;
    }

    public JTextField getTxtListarEmail() {
        return txtListarEmail;
    }

    public void setTxtListarEmail(JTextField txtListarEmail) {
        this.txtListarEmail = txtListarEmail;
    }

    public JTextField getTxtListarGenero() {
        return txtListarGenero;
    }

    public void setTxtListarGenero(JTextField txtListarGenero) {
        this.txtListarGenero = txtListarGenero;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnhadir;
    private javax.swing.JButton btnAnhadirAlbum;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrarAlbum;
    private javax.swing.JButton btnImagen;
    private javax.swing.JButton btnListarAlbums;
    private javax.swing.JButton btnListarGenero;
    private javax.swing.JButton btnListarListenLIst;
    private javax.swing.JButton btnListarPlayed;
    private javax.swing.JButton btnListarUsuarios;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarAlbum;
    private javax.swing.JComboBox<Albums> cmbAlbums;
    private javax.swing.JComboBox<Users> cmbUser;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JFrame frmAlbums;
    private javax.swing.JFrame frmListados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuAlbums;
    private javax.swing.JMenuItem mnuListas;
    private javax.swing.JTextField txtAlbumNombre;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtContrasenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JLabel txtImagen;
    private javax.swing.JTextArea txtListarArea;
    private javax.swing.JTextField txtListarEmail;
    private javax.swing.JTextField txtListarGenero;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
